pacstrap_pkg:
  - base
  - base-devel
  - linux
  - linux-firmware
  - linux-headers
  - btrfs-progs
  - git
  - neovim
  - nano
  - mesa
  - bash-completion
  - xorg
  - xorg-server
  - egl-wayland
  - efibootmgr
  - xdg-user-dirs
  - xdg-utils
  - alsa-utils
  - pipewire
  - pipewire-jack
  - pipewire-alsa
  - pipewire-pulse
  - os-prober
  - fish

extra_pkg:
  - vlc
  - bluez
  - bluez-utils
  - networkmanager
  - network-manager-applet
  - wpa_supplicant
  - wireless_tools
  - cups
  - bluez-cups
  - cups-pdf
  - dialog
  - mtools
  - dosfstools
  - openssh
  - rsync
  - reflector
  - virt-manager
  - qemu
  - qemu-arch-extra
  - edk2-ovmf
  - bridge-utils
  - dnsmasq
  - vde2
  - openbsd-netcat
  - iptables-nft
  - ipset
  - firewalld
  - flatpak
  - ntfs-3g
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-jetbrains-mono
  - ttf-fira-code
  - ttf-fira-mono
  - ttf-fira-sans
  - vivaldi
  - vivaldi-ffmpeg-codecs
  - neofetch
  - htop

intel_cpu_pkg:
  - intel-ucode

amd_cpu_pkg:
  - amd-ucode

nvidia_gpu_pkg:
  - nvidia
  - nvidia-utils
  - nvidia-settings

amd_gpu_pkg:
  - vulkan-radeon

grub_pkg:
  - grub
  - grub-btrfs
