pacstrap_pkg:
  - base
  - base-devel
  - linux
  - linux-firmware
  - linux-headers
  - btrfs-progs
  - git
  - neovim
  - nano
  - mesa
  - bash-completion

intel_cpu_pkg:
  - intel-ucode

amd_cpu_pkg:
  - amd-ucode

nvidia_gpu_pkg:
  - nvidia
  - nvidia_utils
  - nvidia_settings

amd_gpu_pkg:
  - vulkan-radeon
