pacstrap_pkg:
  - base
  - base-devel
  - linux
  - linux-firmware
  - linux-headers
  - btrfs-progs
  - git
  - neovim
  - nano
  - mesa
  - bash-completion
  - xorg
  - xorg-server
  - egl-wayland

intel_cpu_pkg:
  - intel-ucode

amd_cpu_pkg:
  - amd-ucode

nvidia_gpu_pkg:
  - nvidia
  - nvidia-utils
  - nvidia-settings

amd_gpu_pkg:
  - vulkan-radeon
